# Generated by Django 6.0.5 on 2026-05-12 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operatortickettype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='called_window_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Создан'), ('called', 'Вызван'), ('started', 'Начато обслуживание'), ('completed', 'Обслужен'), ('no_show', 'Не явился'), ('cancelled', 'Отменён')], max_length=30),
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_number', models.PositiveIntegerField(unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='operatortickettype',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='tickets.operatorprofile'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='current_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tickets', to='tickets.operatorprofile'),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_events', to='tickets.operatorprofile'),
        ),
        migrations.AddConstraint(
            model_name='operatortickettype',
            constraint=models.UniqueConstraint(fields=('operator', 'ticket_type'), name='unique_operator_ticket_type'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('ticket_type', 'service_date', 'number'), name='unique_ticket_number_per_type_per_day'),
        ),
    ]
