# Generated by Django 6.0.5

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_operatortickettype_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="service_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
